import React from 'react';
import Head from 'next/head';
import { Navbar } from './Navbar';


export const Layout = ({ children }: any) => {
    return (
        <React.Fragment>
            <Head>
                <title>Pokecatch</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/pokeball.png" />
            </Head>
            <header>
                <Navbar />
            </header>
            <main className={` bg-white  p-[10px] `}>
                {children}
            </main>
        </React.Fragment>
    );
    }